### ISSUE TITLE
[Bug] - Won't Create Repo in Organization

### ISSUE THREAD

**Issue by m-sterspace** [microsoft/vscode-azurestaticwebapps#106]
When I try and create a new static web app, I select my organization from github as where I want to create it, but if I go to create a new repository, that repo is created under my personal account. 
1. ![image](https://user-images.githubusercontent.com/37154205/82593391-716f8d80-9b70-11ea-9534-a36cacbc4d23.png)

2. ![image](https://user-images.githubusercontent.com/37154205/82593455-8a783e80-9b70-11ea-8f6a-d8236d3ce253.png)

but the repo it creates ends up being under my personal m-sterspace org:

![image](https://user-images.githubusercontent.com/37154205/82593664-db883280-9b70-11ea-940d-0c902d7b3c5e.png)

If I select and existing repo in my organization it works, but it seems to always create the new one in my personal org.

Also, if there isn't already a branch in an existing repo, it rather unceremoniously exits, it would be nice if it defaulted to creating a master branch for you.

**Comment by nturinski** [comment]
Hi @m-sterspace

Thanks for using the new extension!  I had a quick question regarding this part of your issue

> Also, if there isn't already a branch in an existing repo, it rather unceremoniously exits, it would be nice if it defaulted to creating a master branch for you.

So I was looking into this, and I don't know if the GitHub API will let us create a branch for you in an empty repository since technically nothing has been initialized yet.

We are discussing about having the option of pushing your local workspace project when you create a new repo.  Maybe we can do something similar when we see that a repo is empty?

Thanks for your feedback! 😄

**Comment by m-sterspace** [comment]
Even just a warning message or something would be helpful ... if I remember correctly, I believe that when I ran through it the first time it just didn't create anything but didn't explain why it hadn't worked or present me with an error? I think I just went on a hunch that it was probably because the repo wasn't initialized yet but that may not be as obvious to someone else! 😃

**Comment by nturinski** [comment]
I think the current experience for me is it gets to the branch step, but has nothing listed (but at allows you to go back)

![image](https://user-images.githubusercontent.com/5290572/83804921-c2e54580-a663-11ea-821f-a3ac8d8a13a2.png)

Which I agree is a non-obvious error since there's no way to know whether or not it just didn't load or some other problem occured.

Thanks very much for your response!  The first part of your issue is resolved and we should be releasing a patch update soon that will include that fix, as well as removing the requirement of using Insiders, so please look forward to that. 😁

**Comment by m-sterspace** [comment]
Yep, it does the same thing for me, I should have clarified and said "the experience if you just repeatedly hit enter to blindly accept all the defaults", because then you hit enter on that line and nothing happens 😛

**Comment by nturinski** [comment]
Closing as fixed-- other issue has been filed here: https://github.com/microsoft/vscode-azurestaticwebapps/issues/117
