### ISSUE TITLE
[Discussion] Basic Create vs. Advanced Create

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurestaticwebapps#131]
Related to: https://github.com/microsoft/vscode-azurestaticwebapps/issues/19

What would be the distinction here?  Here are some ideas that I had:

- Automatically pick app folder for the user
  - If we detect an 'app' folder, then we use 'app' as the default location, otherwise leave it as '/'.  However, since this is the only required field, I think it also makes sense to remain as a prompt (but still do the detection logic mentioned earlier)
- Automatically select api and app artifact folders
  - These are both not required fields so I think we can automatically select for users.  I think if the api folder doesn't exist, it won't break the project since Functions isn't a requirement anyway.
  - If the users have settings associated with the project, we can always use those values instead
- We have the remote logic, but I think if the user is using basic create, it makes sense to default to 'master' branch.  My logic being that 'master' should equal 'production' for most users' scenarios.  If they try to create a SWA with a repo that is already using the master branch, it will fail, but that seems logical to me since I don't think it's recommended to have multiple apps linked to the same repo (that's the point of having branches/environments)
- We can probably default the location as well.  It being new, I don't know what the concern is of overpopulating regions.  That being said, we can also try some logic to pick the nearest Region since there are only like 5 to choose from.

If we implement Basic Create to use all of these, we can consistently drop it from 6-8 prompts to 1-5 prompts.

If we remove all the prompts I suggested, the new flow would be:
- name
- org (if no repo detected)
- repo (if no repo detected)

If we keep some of the prompts:
- name
- org (if no repo detected)
- repo (if no repo detected)
- app folder
- location

So that would bring us down to 1-3 prompts or 3-5 prompts.  Either way, I think decreasing the prompts (currently 6-8) by >50% would make creating the app way easier.  I'm just worried at how many of those apps would actually work...

I imagine what we have today is basically advanced create.  Any point where we can find a default value, we should put it as the placeHolder value, but not automatically select anything for users so that they don't get stuck in case the settings are wrong.

**Comment by nturinski** [comment]
@fiveisprime @EricJizbaMSFT  Please rip my idea to shreds and rebuild it even stronger 🔥🥚🐦

**Comment by fiveisprime** [comment]
I support this idea, it's just a matter of figuring out which prompts can be removed _with certainty_ while maintaining a high level of success with the defaults.

> Automatically pick app folder for the user
> **If we detect an 'app' folder, then we use 'app' as the default location, otherwise leave it as '/'.** However, since this is the only required field, I think it also makes sense to remain as a prompt (but still do the detection logic mentioned earlier)

This seems like the most logical and helpful imo. If we look at this through the lens of "most developers are coming with just a SPA app", they end up on a good path with minimal prompt friction. 

> Automatically select api and app artifact folders

This one seems hard given how many possible options there may be. Is this something that would have to change regularly to support various frontend frameworks?

**Comment by nturinski** [comment]
> This one seems hard given how many possible options there may be. Is this something that would have to change regularly to support various frontend frameworks?

Yeah, I was basing this solely on the fact that the portal does not require these fields.  I think for api, it should be independent of the framework since it's literally a functions project, and it'll rely on the routes.json (which would probably be framework dependent).  The portal also defaults the value to 'api'.

As far the build, that one seems difficult, but the portal will default to whatever the app folder is if it is left empty with a placeholder providing examples.

> This seems like the most logical and helpful imo. If we look at this through the lens of "most developers are coming with just a SPA app", they end up on a good path with minimal prompt friction.

One part of the question that is left unanswered is do we even prompt the user then?  I'm leaning towards yes since it's required and pretty crucial for it to run successfully, but would like to know your thoughts.

**Comment by johnpapa** [comment]
Some thoughts on **basic mode**:

**shortest** possible flow, IMO:
1. github repo URL (covers org, repo, even branch if they include it)
2. app location ( we can scan the repo for app, and suggest, but we should not choose it IMO)

I really like not having to enter or and repo separately. GH users are very familiar, I argue, with copying and pasting a GH url. And avoiding two prompts for one ... I think is worth considering. I don't have a problem with the two prompts if you see fit to keep it, but I wanted to toss this up there.

name ... we dont have to ask them for a name. we can give it a name based on the funky name of the SWA URL. WHy not? For basic wizard it would eliminate yet another step. And make it easier to relate the resource to the URL.

**app artifact location**
This folder is different based on the web framework. That's why it must be filled in by the user. But wait ... if we detect the web framework type, we can say "hey, we think this should be the public folder and you are using Svelte" and prompt them with that. And give them the option to change it.


**random thoughts**
1. branch - in basic mode it should use the default branch, IMO.
2. name - we use a generated name based on the SWA URL (ex: snowy-trees)
3. api or functions should be the default (we look for those 2 only)
4. we dont ask for resource group nor location in basic mode

**Comment by nturinski** [comment]
I think I'm going to close this for now.  I think we're at a pretty good place for basic create now.  I do want to add an option for able to create the SWA from the github repo, so I'll add that as a separate issue since it shouldn't be limited to basic create.
