### ISSUE TITLE
The name of workflows are inconsistent between the GitHub webpage and VS Code

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#184]
**OS:** Win10
**Build Version:** 20200812.1

**Repro Step:**

1. Create a Static Web App.
2. Create an Environment by the following commands:
 ```
 git checkout -b new
 git add .
 git commit -m 'api'
 git push origin head
 ```
3. Go to GitHub -> Compare changes between the "master" and "new" branch -> Create a pull request like the following:
![image](https://user-images.githubusercontent.com/62053665/90105342-50d26080-dd78-11ea-9931-6cbf1de8517e.png)
4. Go to the Actions tab and check the name of workflows.
5. Go to the new environment in VS Code -> Expand the Actions tab and check the name of workflows.

**Expect:**
The name of workflows are consistent between the GitHub webpage and VS Code.

**Actual:**
The name of workflows are inconsistent between the GitHub webpage and VS Code.
![image](https://user-images.githubusercontent.com/62053665/90105020-cb4eb080-dd77-11ea-93fe-30236308b9ee.png)

**Comment by nturinski** [comment]
So the cause of this is because GitHub Actions is using the PR name for the actions not on production whereas we list everything by the commit message.

We did that because for the default branch, whenever you push a commit to the production branch, it is listed by the commit name (makes sense since there's no PR title to use here)

@fiveisprime My question is do we want to mimic this behavior?  GitHub probably does it because all of their actions are all listed under one giant list.  We filter the actions out by which branch it relates to, so I don't think having a bunch of actions named after the PR title are particularly useful-- but it could make it difficult to find it on GitHub.  Though, once we implement looking at the job logs through the extension, I'm not sure if you'd go to GitHub anyway.

**Comment by nturinski** [comment]
I prefer this behavior as the commit message is more specific.  I think that it'll end up being more useful for users.

**Comment by EricJizbaMSFT** [comment]
Lol "Fix IBuildPresets" or "Change awkward english" is better than "Changing references to App Artifact to Output Location" (from https://github.com/microsoft/vscode-azurestaticwebapps/pull/259)

People got some weird commit messages...
