### ISSUE TITLE
After Revoking GitHub access no longer useable. Need to change GitHub Org.

### ISSUE THREAD

**Issue by LarouexSoftwareDesign** [microsoft/vscode-azurestaticwebapps#197]
- Configuring for the first time, opened Edge, signed into of my GitHub orgs.
- Authorized.
- Realized it was not the Org I wanted.
- Un-authorized the VS-Code App.
- Uninstalled extension and re-installed.
- Cannot get beyond "Bad Credentials" error in extension.

I checked extension settings and it was not obvious how to fix and uninstall does not get me to re-enter creds.

**Comment by nturinski** [comment]
Hi @LarouexSoftwareDesign 

Sorry you're having issues.  How did you unauthorize VS Code? via Github?  You'll have to sign-out of GitHub from VS Code as well.  You can do that by clicking this profile button at the bottom left:
![image](https://user-images.githubusercontent.com/5290572/92518171-c93c0e00-f1cc-11ea-94b0-9b08137d42ac.png)
![image](https://user-images.githubusercontent.com/5290572/92518194-d0fbb280-f1cc-11ea-8d09-bb817c0ffca0.png)

I agree that it's not super obvious how to fix. Hope this resolves your problem.

**Comment by nturinski** [comment]
Will direct users to sign out of GitHub command if we encounter this error.

**Comment by nturinski** [comment]
Moving this to next milestone until logout command is added back to VS Code API.

**Comment by nturinski** [comment]
Tracking here: https://github.com/microsoft/vscode/issues/115761

**Comment by nturinski** [comment]
Logout seems unlikely, so we can just direct users to reauthorize their GitHub credentials for now.

**Comment by nturinski** [comment]
Looking into this further, I don't think the tradeoff for directing users to reauthorize their GitHub credentials or logging out is worth the cost.  The reasons being:

1. In order to detect stale credentials, we would have to check VS Code's access token against the GitHub API every time we retrieve it.  This could be somewhat expensive for all users with what seems to be a pretty edge case.
2. This only seems to happen if you go to GitHub's settings and unauthorize GitHub for VSCode ![image](https://user-images.githubusercontent.com/5290572/117368484-72c8c180-ae78-11eb-822e-8e8adbabdd65.png)
3. This is resolved if you restart VS Code.  On the next attempt, VS Code will verify the token, see that it's invalid, and prompt for the user to login again.
