### ISSUE TITLE
Add the pick list for the build presets

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-azurestaticwebapps#211]
The portal has been updated to allow the user to select the build presets. These populate the app locaiton, api location, and the app artifact location. see below for details

![image](https://user-images.githubusercontent.com/1202528/93832323-5ce8f200-fc43-11ea-894a-bde32e54bcf0.png)

![image](https://user-images.githubusercontent.com/1202528/93832372-8275fb80-fc43-11ea-8d93-7534c39df845.png)

cc @fiveisprime as per our conversation

**Comment by nturinski** [comment]
Did a little bit of investigating and these values are all hard-coded right now.  The team is using this table as a reference: https://docs.microsoft.com/en-us/azure/static-web-apps/front-end-frameworks

We can do the same, maybe have a learn more link directing them to the table.  If they hit Custom, then they'll get the 3 prompts as usual, otherwise we'll use the presets and skip the prompts.

**Comment by johnpapa** [comment]
cool.

This will evolve, I am sure. But I think this is a great step forward.
