### ISSUE TITLE
Should create SWA in the current branch

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-azurestaticwebapps#276]
1. I started with a branch `main`
1. I created a new branch named `test1`  and pushed to github
1. I made sure I was on the `test1` branch in vs code
1. in vs code, I used this extension to create a new SWA
1. I chose custom and filled in accordingly

The extension added the github workflow file to my main branch

I expected it to create it in the branch I was in

**Comment by nturinski** [comment]
Hi @johnpapa

Just to verify, you created a local branch, pushed it up to GitHub, and then used the "connect to existing repo" deployment method with basic create, correct?

Whenever we do a basic create, we assume the user's branch to be whatever GitHub deems as the default branch of the repository.  We do this because we assumed if users were making a static web app, that's probably what they do would (as production) and make builds based on the other branches.  Do you think we should change this behavior?

(Note, if you'd like to use a separate branch, advanced creation is available)

**Comment by johnpapa** [comment]
Hi

I'm not familiar with  "connect to existing repo"

I am using a branch that is NOT the default. And I wanted to use that to publish. So when I created the SWA it used my default branch, which was confusing because I purposefully didnt want to do that. 

I do think the default behavior should be to use the branch we are on. If I am working in a specific branch, and I create a SWA with the extension, it seems unexpected to create the SWA on another branch. Options:

1. leave as-is 
2. use current working branch in vs code
3. if current working branch is different than default branch, prompt the user
4. prompt the user

1 feel confusing to me, thus this issue :)

2 feels right to me, though maybe I'm not considering all aspects

3 and 4 feel too invasive to me. Perhaps advanced create can do something there.


Side note for context  - As you are aware, Azure SWA supports having a specific branch. meaning I can have 2 SWA apps, each pointing to the same repo on different branches (each with their own github workflow files).

**Comment by nturinski** [comment]
Okay, I understand.  By the way, v0.5.0 released yesterday.  It doesn't resolve this issue, but it does have some other things that might making the creating process a little smoother/easier

**Comment by johnpapa** [comment]
Yeah, I was excited to see 0.5.0, thanks!

I should have mentioned that the above issue is for 0.5.0

**Comment by nturinski** [comment]
This issue has been resolved with v0.7.0 although we did end up with solution 3.
