### ISSUE TITLE
AZ9898

### ISSUE THREAD

**Issue by a888882** [microsoft/vscode-azurestaticwebapps#279]
Does this occur consistently? 
Repro steps:

1.
2.

Action: staticWebApps.action.rerun
Error type: 403
Error Message: This workflow run cannot be rerun

Version: 0.5.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:1151:1761extension.bundle.js:1151:1761
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Hi @a888882 

Thanks for reporting.  Some workflows can't be rerun due to being too old or you not having the property access rights to do so.  This error is coming from GitHub, so I don't think there's much that the extension can do to change this.

If you should have the access-rights to do this and this is an error on our parts, please re-open and provide detailed repro steps.
