### ISSUE TITLE
[GitHub Codespaces] Skip the steps about how to create a static web app when creating a new static web app with basic

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurestaticwebapps#283]
**OS:** Win 10
**Build Version:** 20201215.1
**Environment:** GitHub Codespaces (local)

**Repro steps:**
1. F1 --> Click "Create Static Web App...".
2. Check the next step.

**Expect:**
A prompt about how to create a static web app pops up.
![image](https://user-images.githubusercontent.com/57662131/102451750-181efc80-4074-11eb-9bda-c94656a5d7a4.png)

**Actual:**
No prompt about how to create a static web app pops up.

**Comment by nturinski** [comment]
I think that this happening regardless of Codespaces or not, it's just with Codespaces you are likely using a GitHub repo that you have owner access to so it is automatically selecting `Use existing GitHub repository` for you.  This is the expected behavior.

This behavior should reproduce if you use the same project in a local VS Code instance.

As per the wiki
> [In a basic create, if your currently opened project is connected to a GitHub repo that you own, then it will automatically select this repository for you.
If this behavior is not desired, then you can use advanced creation or close the current project](https://github.com/microsoft/vscode-azurestaticwebapps/wiki/Creating-a-Static-Web-App#use-an-existing-github-repository)

**Comment by nturinski** [comment]
Closing due to lack of response.  I assume that this is the by-design behavior in which it's automatically connecting to your repo because it lives up in GitHub.
