### ISSUE TITLE
VS Code failed to execute git

### ISSUE THREAD

**Issue by SafiyK98** [microsoft/vscode-azurestaticwebapps#308]
Does this occur consistently? 
Repro steps:

1. try to create new git project via vs code
2.

Action: staticWebApps.createStaticWebApp
Error type: S
Error Message: Failed to execute git

Version: 0.5.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.54.1
Language: en

**Comment by nturinski** [comment]
It seems like there's problems with the git steps at the end of publishing.

In order to publish your repo, we use a git push to push the contents to GitHub. Could you post your logs from the output channel? I'd like to see what step that this process is failing at.

Related to this: https://github.com/microsoft/vscode-azurestaticwebapps/issues/290

**Comment by anthonychu** [comment]
@nturinski I just ran into the same thing and have a repro:

```
10:18:15 PM: Creating new public GitHub repository "20210407-vueapp"...
10:18:16 PM: Created new public GitHub repository "20210407-vueapp".
10:18:16 PM: Pushing local branch "main" to GitHub repository "20210407-vueapp"...
10:18:17 PM: Error: Failed to execute git
10:18:56 PM: Creating resource group "anthonychu-20210407-vueapp" in location "westus2"...
10:18:56 PM: Successfully created resource group "anthonychu-20210407-vueapp".
10:18:56 PM: Creating new static web app "anthonychu-20210407-vueapp"...
10:19:02 PM: Successfully created new static web app "anthonychu-20210407-vueapp".  GitHub Actions is building and deploying your app, it will be available once the deployment completes.
10:20:28 PM: Deployment for "anthonychu-20210407-vueapp" has failed. Commit and push changes the GitHub repository to create a new deployment.
```

Looks like the problem is because there are uncommitted changes in the repo.

I committed the changes and tried again. This time it "worked", but problem was that it didn't push my changes and just created the SWA using the empty repo. 🙁

I think we discussed ensuring the repo is clean before creating a SWA. I think that's a good idea.

**Comment by nturinski** [comment]
@anthonychu Got it, thanks for the repro!

Just to verify, you created the new repo from the extension while it was empty.  The creation failed, but a GitHub was created. Then you committed without pushing and created the SWA again using the repo (20210407-vueapp) that was just created?

I just wanted to make sure that this wasn't a timing issue or anything.

**Comment by anthonychu** [comment]
@nturinski I think these steps should repro it:

```
git init
touch index.html
```

Then go through the SWA create command in the extension. It'll ask for some info about the GitHub repo to create, then ask about the SWA. Then it appears to create the repo just fine, but for some reason it can't push because of uncommitted changes and just blows up.

I should be clear that those logs are from running the create SWA command two separate times. After the above steps, these are the logs:

```
10:18:15 PM: Creating new public GitHub repository "20210407-vueapp"...
10:18:16 PM: Created new public GitHub repository "20210407-vueapp".
10:18:16 PM: Pushing local branch "main" to GitHub repository "20210407-vueapp"...
10:18:17 PM: Error: Failed to execute git
```

At this point the user is in a spot that it's hard to recover from. They'll likely try running the create SWA command again (as I did). This time, it'll take the empty repo that was created and create a SWA with it. This adds a workflow to the empty repo, which will fail deployment.

```
10:18:56 PM: Creating resource group "anthonychu-20210407-vueapp" in location "westus2"...
10:18:56 PM: Successfully created resource group "anthonychu-20210407-vueapp".
10:18:56 PM: Creating new static web app "anthonychu-20210407-vueapp"...
10:19:02 PM: Successfully created new static web app "anthonychu-20210407-vueapp".  GitHub Actions is building and deploying your app, it will be available once the deployment completes.
10:20:28 PM: Deployment for "anthonychu-20210407-vueapp" has failed. Commit and push changes the GitHub repository to create a new deployment.
```

Because the local repo and GitHub are totally diverged, the recommendation from the last step to push changes again won't work (it'll require a force push, and the repo won't have the workflow). I think the fix at this point is to manually copy the workflow from the GitHub repo to the local repo. Commit, and force push.

**Comment by anthonychu** [comment]
@nturinski @fiveisprime I've been running into this quite a bit. It's hard to remember to commit before starting the create SWA command. Can we reopen this and try to address in 0.7.0? Thanks.

**Comment by nturinski** [comment]
@anthonychu This PR actually addresses this problem: https://github.com/microsoft/vscode-azurestaticwebapps/pull/335.

We're planning to make having a clean repository opened in VS Code a prerequisite to creating a static web app.  If you'd like to know more about the specifics of what we're requiring, feel free to ping me and I can fill you in on the details.
