### ISSUE TITLE
Feature Request: Kick off the GitHub Action from this VS Code Extension

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-azurestaticwebapps#401]
Scenario:

I have a SWA open in vs code and I am in the extension viewlet. I can see the production github aciton node. I make a change to the workflow file, but the Action doesn;t monitor that file (based on my config). So I want to restart the action. Today, I have to go to the browser on GitHub to do this or make a meanlingless commit.

Another reason to do this is if the action fails for some reason and I want to restart it.

idea:

Perhaps we could have a right click option on one of the nodes to kick off the Action again.

**Comment by nturinski** [comment]
Hi @johnpapa

Does this "Rerun Action..." command not satisfy your request?   
![image](https://user-images.githubusercontent.com/5290572/118551925-1e90cd80-b713-11eb-9007-9b15dbb1e9ea.png)

Rerun should be able to kick off an action again.

The scenario you described where you change the workflow file: I'm not sure if there is anything that we can do about that from the extension.  Because the Actions are linked to the GitHub repo, any local changes to the workflow file won't affect the static web app.  We _could_ commit any changes to the workflow file for the user to automatically update their config in the repo, but that is not an option that we have explored.

**Comment by johnpapa** [comment]
ah, I didnt click far enough down. That is perfect, thanks.

I clicked on the 3 nodes above it (see image below). But I think I just messed up.

**Comment by nturinski** [comment]
Great, thanks for the response John!  I'll go ahead and close this issue then.
