### ISSUE TITLE
Current branch has changes, change create SWA?

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-azurestaticwebapps#402]
If I have unsaved changes on my local branch (not default branch), I can't seem to create a SWA. For me, the local branch isn't used for my SWA so I'm not sure why it stopped me from creating a SWA. Additionally it creates a settings file for the SWA. I thought .vscode/settings files were meant for local development. I either have to revert or check in. Why would I want to check it in?

**Comment by nturinski** [comment]
Hi @diberry.  Thanks for the questions and feedback!  After a lot of discussion, we came to the conclusion that having the user check out the branch they wish to deploy and having it be a clean workspace was the best decision for our users.

Here are the reasons we require that the workspace tree be clean:
- We do a `git pull` to retrieve the newly created workfile configuration yml file immediately after creation. Having a clean tree makes this process easier and ensures that users will be able to get the workflow file locally.
- We don't enforce that users have to create a SWA with their default branch even though we recommend it.  A branch is a requirement for SWA creation, so we currently used the checked-out branch.  We could technically set the branch without checking it out, but it makes our `git pull` logic easier and the entire flow more consistent.  But we can revisit this user scenario design.
- The local settings file is useful if the repo is cloned down to another machine and used to create a SWA.  It will pre-fill the defaults for the app/api/output location so that the workflow config settings should always be consistent across dev environments.  We have plans to use these settings for the SWA emulator as well, which will be a local development scenario.

I hope this addresses your questions.  Please let me know if I can clarify or expand upon any of these points. 😃

**Comment by nturinski** [comment]
Hi @diberry 

I'm going to go ahead and close this now since you haven't had any follow-up questions.  Please feel free to re-open if there are any other questions/concerns that I can help resolve!
