### ISSUE TITLE
Extension constantly asking for my Github permissions, at all levels of the hierarchy

### ISSUE THREAD

**Issue by jlengrand** [microsoft/vscode-azurestaticwebapps#413]
Hey there, 

I've created my first Azure Static Web App via the extension, and every time I start vscode and try to use the Azure hierarchy I get asked for a Github sign-in _at each level of the hierarchy_.
I'm not sure this is the intended behaviour? 

You can see it happen live over here : https://www.twitch.tv/videos/1035650436?t=00h38m41s (at the 38m41sec mark)

What I expect : 

* My approval / sign in is cached across sessions
* My approval is cached across levels of the hierarchy and I don't have to sign up 7 times in a row. 

Versions: 
* vscode : Version: 1.57.0-insider (Universal)
* AzureStaticWebApps extension : latest? 

![image](https://user-images.githubusercontent.com/921666/120827849-2a2a2400-c55c-11eb-9021-726203808ab4.png)

**Comment by nturinski** [comment]
Hi @jlengrand.  Watched the stream-- really cool to watch you run through the extension via Twitch!

So you mentioned that you did a clean install of VS Code and I watched you download the latest version of extension and yeah, that is definitely unintended behavior.  You shouldn't have to confirm access to GitHub that many times (it should be one and done).  

You can see the code that we run [here](https://github.com/microsoft/vscode-azurestaticwebapps/blob/main/src/utils/gitHubUtils.ts#L39-L51) is actually getting the token from VS Code.  If it is created, it should be a simple fetch from cache. Otherwise it'll prompt and create it for you.

I haven't been able to reproduce this personally, but I have two ideas that we can investigate:  

The first is if you go to the bottom left, you can manage your accounts that are signed into VS Code.  I don't know why it wouldn't check this by default once you confirm, but maybe this is preventing us from getting the token?

![image](https://user-images.githubusercontent.com/5290572/120860649-df4be480-c53a-11eb-8df1-8e7ac3613442.png)

![image](https://user-images.githubusercontent.com/5290572/120860670-e70b8900-c53a-11eb-89d2-284f7c871fec.png)

The other idea is that you'll notice the first time you authorize GitHub, the confirmation dialogue looks slightly different:
![image](https://user-images.githubusercontent.com/5290572/120860514-a6ac0b00-c53a-11eb-9b39-71738c7f30ab.png)

I tried re-authorizing VS Code for using GitHub (by deleting it from my trusted apps in my GitHub account) and my prompt didn't have that checkbox for "Don't ask again."  I didn't see anything in my user/workspace settings that would control that behavior so I can't test that personally, but maybe that would allow us to grab the token without prompting you each time?
