### ISSUE TITLE
[Codespaces] There is a confused dialog after opening the cloned repository in a new window

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#416]
**Environment:** Remote Codespaces
**Build Version:** 20210609.3

**Repro Steps:**

1. Right click a static web app -> Select "Clone Repo..." -> Click "Open in New Window" when asking to open the cloned repository -> Open a new window in browser.
    ![image](https://user-images.githubusercontent.com/62053665/121506583-6ce57380-ca16-11eb-8d28-ddbc14309168.png)
2. Return to the previous window.
3. Check whether there is a confused dialog.

**Expect:**
There is no confused dialog.

**Actual:**
There is a confused dialog.
![image](https://user-images.githubusercontent.com/62053665/121506545-6525cf00-ca16-11eb-8aa0-0600267638a7.png)

**More Info:**
Steps details:
![44](https://user-images.githubusercontent.com/62053665/121506484-563f1c80-ca16-11eb-994c-55387219c05f.gif)

**Comment by nturinski** [comment]
This is by-design.  Since Codespaces is running in the browser, VS Code requires user permission to open a new tab.  If you click "Open", it should grant access and the window should open.

You can see that it is planned behavior in this issue: https://github.com/microsoft/vscode/issues/122354

Also, this is somewhat external since the dialogue and command are both coming from the Git extension.  We don't actually control that behavior, we are just calling its `git.clone` command.
