### ISSUE TITLE
Add Location step to the normal create scenario

### ISSUE THREAD

**Issue by gagarine** [microsoft/vscode-azurestaticwebapps#429]
Creating a new Azure Static Web App from VS doesn't seem to offer a way to set the region.

How the region is selected?

**Comment by gagarine** [comment]
Also it seem Static Web App are only available on Central US, East US 2, West US 2, East Asia, and West Europe Azure regions. This is the only region available when I create the Static Web App from the Azure portal.

**Comment by nturinski** [comment]
In order to select a region, you'll have to use the `Create a Static Web App... (Advanced)` command.  The last prompt will be location:

![image](https://user-images.githubusercontent.com/5290572/124308311-fa038000-db1d-11eb-8c4c-b60a6d440219.png)

**Comment by gagarine** [comment]
Thanks. In my head, region is basic and not advance at all ;) .

I think this advance/not advance things is not super user friendly. Why not removing this difference and propose only one command with default (recommended) option?

Feel free to close the issue.

**Comment by nturinski** [comment]
Hi @gagarine, thanks for the feedback!  We will strongly consider moving location back to the normal create experience.

Yeah, I agree that region is a pretty basic!  But we figured it was something we could automatically select for users without breaking them.  A big part of our design philosophy is to reduce the number of unnecessary prompts so that users can get their static apps up-and-running asap.

We offer the advanced/normal create scenarios because some users like having more flexibility when creating their apps such as selecting the resource group, but we believe that most users probably don't have a strong preference about this.
