### ISSUE TITLE
The default value of the application location remains unchanged when creating a static web app again

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#438]
**OS:** All
**Build Version:** 20210707.11

**Repro Steps:**

1. Create a static web app -> Enter "`app`" when asking to enter the location of the application code.
2. Create the second static web app with same selections.
3. Check whether the default value of the application location changes to "`app`".

**Expect:**
The default value of the application location changes to "`app`".
![image](https://user-images.githubusercontent.com/62053665/124902602-aa3d2100-e015-11eb-8edf-816a1916693a.png)

**Actual:**
The default value of the application location remains unchanged.
![image](https://user-images.githubusercontent.com/62053665/124902518-95608d80-e015-11eb-8a87-4c566daf7fd1.png)

**More Info:**
This issue doesn't reproduce on the previous release build 0.7.0.

**Comment by nturinski** [comment]
I'm glad that you could notice the change!  This is by-design though.  We no longer set the configurations on creating a static web app, but we still support the VS Code settings.

This was a choice we made because the settings did not seem to have much benefit to users.   The fact that their `.vscode/settings.json` was dirty immediately after creating their SWA was also confusing.  The most common use case we could  see for the settings is for tutorials/forking someone's repo, but in that case, they may manually set the location settings and include it in their project.
