### ISSUE TITLE
Cannot select the environment when executing the "Open in GitHub" command from command palette

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#503]
**OS:** All
**Build Version:** 20210827.7
**Regression:** Not a Regression

**Repro Steps:**

1. Expand a static web app -> Environment ->Right click the "Actions" node -> There is the "Open in GitHub" command.
2. F1 -> Azure Static Web Apps: Open in GitHub -> Select a subscription -> Select a static web app.
3. Check whether the next step is to select the environment.

**Expect:**
The next step is to select the environment.

**Actual:**
Open the GitHub webpage directly.

**More Info:**
Right click a static web app -> There is no "Open in GitHub" command in the context menu.

**Comment by nturinski** [comment]
The GitHub Actions page on GitHub shows the entire repository (including all branches) so it's not really specific to a build environment.  That's why we only ask the user for a Static Web App.

The reason it exists on each build environment in the tree is because we are able to filter out the actions based on the head_branch, but GitHub doesn't support that view.

**Comment by v-mengwe** [comment]
Got it, thanks for your sharing.
