### ISSUE TITLE
There is an error when debugging the "angular-basic" project

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurestaticwebapps#574]
**OS:** All
**Build Version:** 20211105.14
**Regression:** Not a regression

**Repro Steps:**

1. Clone https://github.com/staticwebdev/angular-basic -> Open the project in VS Code.
2. Open VS Code terminal and run "npm install" -> Go to the "Run and Debug" menu -> Select the "Show all automatic debug configurations." -> Select "Azure Static Web Apps…" -> Select "SWA: Run angular-basic".
3. Check whether there is no error when debugging.

**Expect:**
There is no error when debugging.

**Actual:**
There is an error when debugging.
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/62053665/141102567-e97a01c8-bc98-4f1d-b6c1-d4802a681135.png)

**More Info:**
The opened browser window as below:
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/62053665/141102571-3ddcd2bd-6d2b-4e9b-991b-12f835b9056f.png)

**Comment by alexweininger** [comment]
Will was able to reproduce this issue. And in doing some experimentation with Will, I was able to identify that the issue is that `ng serve` takes long enough on the first run that we need to be using the `--devserver-timeout` flag in the SWA CLI to make sure `ng serve` finishes before the SWA CLI times out. I'll have a fix out soon 🤠 

The SWA CLI command that works: `swa start http://localhost:4200 --run'npm start' --devserver-timeout=100000`
