### ISSUE TITLE
Support .NET 6 Azure Functions

### ISSUE THREAD

**Issue by anthonychu** [microsoft/vscode-azurestaticwebapps#590]
Static Web Apps now supports .NET 6 functions (in-process and isolated). Currently, when using Azure Functions Core Tools V4, we get this error: https://github.com/microsoft/vscode-azurefunctions/issues/3002

**Comment by alexweininger** [comment]
Problem is that we are defaulting to `netcoreapp3.1` [here](https://github.com/microsoft/vscode-azurestaticwebapps/blob/c7371c8082fdd51ebef50af94c31845f6aea05cc/src/commands/createHttpFunction.ts#L37). We started defaulting to 3.1 in https://github.com/microsoft/vscode-azurestaticwebapps/issues/323 because we wanted to prevent .NET 5 apps from being created. 

Assuming we still don't want users creating .NET 5 function apps, we'll need to stop defaulting to 3.1 and allow both 3.1 and .NET 6.
