### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by atlas-github** [microsoft/vscode-azurestaticwebapps#593]
Does this occur consistently? Yes

Repro steps:

1. Install VSCode
2. Install Cognitive Search, and Static Web Apps Extensions. 

Action: staticWebApps.activate
Error type: undefined
Error Message: Unknown Error

Version: 0.9.0
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.63.2
Language: en

**Comment by wwlorey** [comment]
I'm not able to reproduce this on version 1.64.0-insider. I'm blocked from trying in standard VS Code due to https://github.com/microsoft/vsmarketplace/issues/214.

Can you try reproducing with the latest version of [VS Code Insiders](https://code.visualstudio.com/insiders/)? And please let us know any other information about your configuration as well as answering these questions:

1. Are you signed in using your Azure Account in VS Code?
2. Does Azure Cognitive Search activate without errors?

**Comment by alexweininger** [comment]
I wasn't able to reproduce this on stable 1.63.2 (Universal).

In addition to the questions @wwlorey gave, does the Azure Static Web Apps extension activate without errors if you uninstall the Azure Cognitive Search extension?
