### ISSUE TITLE
Git Pull on successful resource creation?

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-azurestaticwebapps#860]
Does the extension perform a Git Pull after it creates the resource? This seems like new behavior.

**Comment by nturinski** [comment]
We have had this behavior for over a year: https://github.com/microsoft/vscode-azurestaticwebapps/pull/692/files#diff-71e8df3edc0b95484e8ea0cfb8fb79ffc32b5160dd9e62fb6717d0e7ee711b07R173.

The idea was we force users to have a clean repo when creating a static web app. Therefore, we should be able to do a git pull without any conflicts. The reason we want to pull down changes is because SWA is automatically creating the .yaml file in their repository, and we want that file to be in their local workspace.
